const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'lunch',
    brand: 'hello world',
    price: 15.99,
    vendor: 'abc limited',
    img: './images/item-1.jpeg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    reviews: 5,
    numReviews: 30,
    ratings: 4,
    countInStock: 0
  },
  {
    id: 13,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    brand: 'hello world',
    price: 15.99,
    vendor: 'abcd limited',
    img: './images/item-1.jpeg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    reviews: 5,
    numReviews: 30,
    ratings: 4,
    countInStock: 10
  },
  {
    id: 18,
    title: 'buttermilk pancakes',
    category: 'lunch',
    brand: 'hello world',
    price: 15.99,
    vendor: 'abcdd limited',
    img: './images/item-1.jpeg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    reviews: 5,
    numReviews: 30,
    ratings: 4,
    countInStock: 10
  },
  {
    id: 34,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    brand: 'hello world',
    price: 15.99,
    vendor: 'abc limited',
    img: './images/item-1.jpeg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    reviews: 5,
    numReviews: 30,
    ratings: 4,
    countInStock: 10
  },
  {
    id: 123,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    brand: 'hello world',
    price: 15.99,
    vendor: 'abc limited',
    img: './images/item-1.jpeg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    reviews: 5,
    numReviews: 30,
    ratings: 4,
    countInStock: 10
  },
  {
    id: 100,
    title: 'buttermilk pancakes',
    category: 'dinner',
    brand: 'hello world',
    price: 15.99,
    vendor: 'abc limited',
    img: './images/item-1.jpeg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    reviews: 5,
    numReviews: 30,
    ratings: 4,
    countInStock: 10
  },
  {
    id: 144,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    brand: 'hello world',
    price: 15.99,
    vendor: 'abc limited',
    img: './images/item-1.jpeg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    reviews: 5,
    numReviews: 30,
    ratings: 4,
    countInStock: 10
  },
  {
    id: 28,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    brand: 'hello world',
    price: 15.99,
    vendor: 'abc limited',
    img: './images/item-1.jpeg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    reviews: 5,
    numReviews: 30,
    ratings: 4,
    countInStock: 10
  },
  {
    id: 3,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    brand: 'hello world',
    price: 15.99,
    vendor: 'abc limited',
    img: './images/item-1.jpeg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    reviews: 5,
    numReviews: 30,
    ratings: 4,
    countInStock: 10
  },
  {
    id: 18,
    title: 'buttermilk pancakes',
    category: 'lunch',
    brand: 'hello world',
    price: 15.99,
    vendor: 'abc limited',
    img: './images/item-1.jpeg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    reviews: 5,
    numReviews: 30,
    ratings: 4,
    countInStock: 10
  },
  {
    id: 5,
    title: 'buttermilk pancakes',
    category: 'lunch',
    brand: 'hello world',
    price: 15.99,
    vendor: 'odofing limited',
    img: './images/item-1.jpeg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    reviews: 5,
    numReviews: 30,
    ratings: 4,
    countInStock: 10
  },
  {
    id: 6,
    title: 'buttermilk pancakes',
    category: 'dinner',
    brand: 'hello world',
    price: 15.99,
    vendor: 'odofing limited',
    img: './images/item-1.jpeg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    reviews: 5,
    numReviews: 30,
    ratings: 4,
    countInStock: 10
  },
  {
    id: 7,
    title: 'buttermilk pancakes',
    category: 'dinner',
    brand: 'hello world',
    price: 15.99,
    vendor: 'odofing limited',
    img: './images/item-1.jpeg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    reviews: 5,
    numReviews: 30,
    ratings: 4,
    countInStock: 10
  },
  {
    id: 9,
    title: 'buttermilk pancakes',
    category: 'Super',
    brand: 'hello world',
    price: 15.99,
    vendor: 'odofing limited',
    img: './images/item-1.jpeg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    reviews: 5,
    numReviews: 30,
    ratings: 4,
    countInStock: 10
  },
  
];
export default menu;
