// REGISTER USER
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

// ACTIVATE USER REGISTRATION
export const USER_ACTIVATION_REQUEST = 'USER_ACTIVATION_REQUEST'
export const USER_ACTIVATION_SUCCESS = 'USER_ACTIVATION_SUCCESS'
export const USER_ACTIVATION_FAIL = 'USER_ACTIVATION_FAIL'

// USER LOGIN
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

// ACTIVATE USER REGISTRATION
export const USER_RESET_REQUEST = 'USER_RESET_REQUEST'
export const USER_RESET_SUCCESS = 'USER_RESET_SUCCESS'
export const USER_RESET_FAIL = 'USER_RESET_FAIL'

// FORGOT PASSWORD
export const USER_FORGOT_PASSWORD_REQUEST = 'USER_FORGOT_PASSWORD_REQUEST'
export const USER_FORGOT_PASSWORD_SUCCESS = 'USER_FORGOT_PASSWORD_SUCCESS'
export const USER_FORGOT_PASSWORD_FAIL = 'USER_FORGOT_PASSWORD_FAIL'

// RESET PASSWORD
export const USER_RESET_PASSWORD_REQUEST = 'USER_RESET_PASSWORD_REQUEST'
export const USER_RESET_PASSWORD_SUCCESS = 'USER_RESET_PASSWORD_SUCCESS'
export const USER_RESET_PASSWORD_FAIL = 'USER_RESET_PASSWORD_FAIL'

// CREATE PRODUCT
export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST'
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS'
export const CREATE_PRODUCT_FAIL = 'CREATE_PRODUCT_FAIL'
export const CREATE_PRODUCT_RESET = 'CREATE_PRODUCT_RESET'

// GET ALL PRODUCTS
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

// UPDATE PRODUCT
export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST'
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS'
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL'
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET'

// GET SINGLE PRODUCT
export const SINGLE_PRODUCT_REQUEST = 'SINGLE_PRODUCT_REQUEST'
export const SINGLE_PRODUCT_SUCCESS = 'SINGLE_PRODUCT_SUCCESS'
export const SINGLE_PRODUCT_FAIL = 'SINGLE_PRODUCT_FAIL'

// GET SINGLE PRODUCT
export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'

// USER UPDATE PROFILE
export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

// GET USER DETAILS
export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

// ADD TO WISHLIST
export const ADD_WISHLIST_REQUEST = 'ADD_WISHLIST_REQUEST'
export const ADD_WISHLIST_SUCCESS = 'ADD_WISHLIST_SUCCESS'
export const ADD_WISHLIST_FAIL = 'ADD_WISHLIST_FAIL'
export const ADD_WISHLIST_RESET = 'ADD_WISHLIST_RESET'

// GET ALL USER PRODUCTS
export const MY_PRODUCTS_REQUEST = 'MY_PRODUCTS_REQUEST'
export const MY_PRODUCTS_SUCCESS = 'MY_PRODUCTS_SUCCESS'
export const MY_PRODUCTS_FAIL = 'MY_PRODUCTS_FAIL'
export const MY_PRODUCTS_RESET = 'MY_PRODUCTS_RESET'

// GET ALL USER PRODUCTS
export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'
export const USER_LIST_RESET = 'USER_LIST_RESET'

// ADMIN UPDATE USER
export const ADMIN_UPDATE_USER_REQUEST = 'ADMIN_UPDATE_USER_REQUEST'
export const ADMIN_UPDATE_USER_SUCCESS = 'ADMIN_UPDATE_USER_SUCCESS'
export const ADMIN_UPDATE_USER_FAIL = 'ADMIN_UPDATE_USER_FAIL'
export const ADMIN_UPDATE_USER_RESET = 'ADMIN_UPDATE_USER_RESET'

// ADMIN GET USER DETAILS
export const ALL_USERS_DETAILS_REQUEST = 'ALL_USERS_DETAILS_REQUEST'
export const ALL_USERS_DETAILS_SUCCESS = 'ALL_USERS_DETAILS_SUCCESS'
export const ALL_USERS_DETAILS_FAIL = 'ALL_USERS_DETAILS_FAIL'
export const ALL_USERS_DETAILS_RESET = 'ALL_USERS_DETAILS_RESET'

// ADMIN CREATE NEW USER
export const ADMIN_CREATE_USER_REQUEST = 'ADMIN_CREATE_USER_REQUEST'
export const ADMIN_CREATE_USER_SUCCESS = 'ADMIN_CREATE_USER_SUCCESS'
export const ADMIN_CREATE_USER_FAIL = 'ADMIN_CREATE_USER_FAIL'

// ADMIN GET ALL PRODUCTS
export const ADMIN_GET_ALL_PRODUCTS_REQUEST = 'ADMIN_GET_ALL_PRODUCTS_REQUEST'
export const ADMIN_GET_ALL_PRODUCTS_SUCCESS = 'ADMIN_GET_ALL_PRODUCTS_SUCCESS'
export const ADMIN_GET_ALL_PRODUCTS_FAIL = 'ADMIN_GET_ALL_PRODUCTS_FAIL'

// ADMIN GET ALL PRODUCTS
export const ADMIN_UPDATE_ALL_PRODUCTS_REQUEST =
  'ADMIN_UPDATE_ALL_PRODUCTS_REQUEST'
export const ADMIN_UPDATE_ALL_PRODUCTS_SUCCESS =
  'ADMIN_UPDATE_ALL_PRODUCTS_SUCCESS'
export const ADMIN_UPDATE_ALL_PRODUCTS_FAIL = 'ADMIN_UPDATE_ALL_PRODUCTS_FAIL'
export const ADMIN_UPDATE_ALL_PRODUCTS_RESET = 'ADMIN_UPDATE_ALL_PRODUCTS_RESET'

// ADMIN CREATE PRODUCT
export const ADMIN_CREATE_PRODUCT_REQUEST = 'ADMIN_CREATE_PRODUCT_REQUEST'
export const ADMIN_CREATE_PRODUCT_SUCCESS = 'ADMIN_CREATE_PRODUCT_SUCCESS'
export const ADMIN_CREATE_PRODUCT_FAIL = 'ADMIN_CREATE_PRODUCT_FAIL'
export const ADMIN_CREATE_PRODUCT_RESET = 'ADMIN_CREATE_PRODUCT_RESET'

// ADMIN DELETE PRODUCT
export const ADMIN_DELETE_PRODUCT_REQUEST = 'ADMIN_DELETE_PRODUCT_REQUEST'
export const ADMIN_DELETE_PRODUCT_SUCCESS = 'ADMIN_DELETE_PRODUCT_SUCCESS'
export const ADMIN_DELETE_PRODUCT_FAIL = 'ADMIN_DELETE_PRODUCT_FAIL'

// ADD TO WISHLIST
export const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST'
export const PRODUCT_CREATE_REVIEW_SUCCESS = 'PRODUCT_CREATE_REVIEW_SUCCESS'
export const PRODUCT_CREATE_REVIEW_FAIL = 'PRODUCT_CREATE_REVIEW_FAIL'
export const PRODUCT_CREATE_REVIEW_RESET = 'PRODUCT_CREATE_REVIEW_RESET'

// USER DELETE ACCOUNT
export const USER_DELETE_ACCOUNT_REQUEST = 'USER_DELETE_ACCOUNT_REQUEST'
export const USER_DELETE_ACCOUNT_SUCCESS = 'USER_DELETE_ACCOUNT_SUCCESS'
export const USER_DELETE_ACCOUNT_FAIL = 'USER_DELETE_ACCOUNT_FAIL'
export const USER_DELETE_ACCOUNT_RESET = 'ADMIN_DELETE_ACCOUNT_RESET'

// ADMIN DELETE ACCOUNT
export const ADMIN_DELETE_ACCOUNT_REQUEST = 'ADMIN_DELETE_ACCOUNT_REQUEST'
export const ADMIN_DELETE_ACCOUNT_SUCCESS = 'ADMIN_DELETE_ACCOUNT_SUCCESS'
export const ADMIN_DELETE_ACCOUNT_FAIL = 'ADMIN_DELETE_ACCOUNT_FAIL'
export const ADMIN_DELETE_ACCOUNT_RESET = 'ADMIN_DELETE_ACCOUNT_RESET'
